// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhgvzqlqipheessplvqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoZ3Z6cWxxaXBoZWVzc3BsdnFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MDExMDYsImV4cCI6MjA3MDE3NzEwNn0.W8c_JpRev9oKODvQRDDdJZNhI12emhP51yRFIuRXYXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});